#
# Vagrant Andible Playbook for Devs
#
---

- hosts: localhost 
  user: vagrant 
  sudo: True
  
  vars:


  tasks:

    - name: Install nginx 
      action: apt pkg=nginx state=installed

#    - name: Intall php 5.3 with Fpm support
#      action: apt pkg=
