---
- hosts: all 
  gather_facts: False
  #sudo: True
  #sudo_user: jamengual
  vars:
    project_name: CheckDesk
    vmbox: MeedanDevVagrant.pkg
    boxurl: http://files.amengual.cl/MeedanDevVagrant.pkg
    git_url: git://github.com/jamengual/ansible-vagrant.git
    #boxurl: url=http://192.168.1.33/~jamengual/MeedanDevVagrant.pkg
    #local_dir: checkdesk
    local_dir: ~/Checkdesk
  #vars_prompt:
  #  - name: "shared_folder"
  #   prompt: "Please enter the folder full path to share with vagrant (Where do you have your code)"
  #   private: False
  tasks:
  #   - action: command whereis vagrant 
  #     register: is_vagrant_installed 

  #   - name: "stop if vagrant is not installed"
  #     action: command echo "Vagrant is not installed!!!!"
  #     only_if: "'${is_vagrant_installed.stdout}'.find('vagrant') != -1"
     - name: Selecting code folder to share with VM
       action: command python directoryselection.py
       register: shared_folder

     - name: Downloading Vagrant package
       action: get_url $boxurl dest=/tmp/$vmbox 
       
     - name: Adding the box to vagrant
       action: command vagrant box add $project_name /tmp/$vmbox

     - name: Creating Vagrant directory $project_name
       action: file state=directory path=$local_dir

     - name: Creating shared folder if doesn't exist
       action: file state=directory path=${shared_folder.stdout}

     - name: Removing Vagrantfile if exist
       action: file state=absent path=$local_dir/Vagrantfile

     - name: Initializing Vagrant directory $project_name
       action: command chdir=$local_dir vagrant init

     - name: Exporting git ansible-vagrant git repo
       action: git repo=$git_url dest=$local_dir/ansible-vagrant version=dev

     - name: Configuring template for Vagrant file
       action: template src=$local_dir/ansible-vagrant/templates/Vagrantfile.j2 dest=$local_dir/Vagrantfile
     
     - name: Creating nginx virtual host config for VM
       action: template src=$local_dir/ansible-vagrant/templates/checkdesk.j2 dest=$local_dir/ansible-vagrant/checkdesk_vhost

     #- name: Adding checkdesk to your host table
      #action: lineinfile name=/etc/hosts regexp=^127.0.0.1 backup=yes
      #action: lineinfile name=hosts regexp="^127\.0\.0\.1.*localhost" line="127.0.0.1\tlocalhost $project_name"

     - name: Starting Vagrant Vm
       action: command chdir=$local_dir vagrant up

     - name: Creating ansible checkout directory on VM
       action: command chdir=$local_dir vagrant ssh -c "sudo mkdir -p /var/lib/ansible/local"

     - name: Changing permisions to checkout directory
       action: command chdir=$local_dir vagrant ssh -c "sudo chown -R vagrant /var/lib/ansible"

     - name: Running ansible pull from first time
       action: command chdir=$local_dir vagrant ssh -c "ansible-playbook --connection=local /ansible/ansible-vagrant/ansible-pull.yml"
